baseURL = "https://chunkofcoal.com"
languageCode = "en-us"
title = "chunkofcoal.com"
theme = "coal"

[pagination]
pagerSize = 50

[taxonomies]
category = "categories"
tag = "tags"

[params]
description = "friendlymatthew's blog about programming, Rust, SIMD, file formats, and databases"
author = "friendlymatthew"
featured_image = "/images/me.jpg"
github = "friendlymatthew"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "github"
noClasses = false

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "feed"
